### ISSUE TITLE
Hey try adding a few more tutorials section on how to delete TileEntities and Entities

### ISSUE THREAD

**Issue by StealthyExpertX** [gentlegiantJGC/MCEdit-Filters#1]
Just a thought since you made these tutorials it might help make it easier for newbies.

**Comment by gentlegiantJGC** [comment]
I don't think I have ever really done that myself which is probably why I never added it.

Would you do
`del val`

or would you need to rebuild the whole list if you are iterating through it?

**Comment by StealthyExpertX** [comment]
Here's A method I made awhile back because the current remove method from
mcedit didn't do the job and left TileEntities behind randomly here and
there.

#Delete TileEntities Method
def deleteAllTiles(box, level, bool, x1, y1, z1):

    if bool == True:
        for x5 in xrange(box.minx, box.maxx):

            for y5 in xrange(box.miny, box.maxy):

                 for z5 in xrange(box.minz, box.maxz):

                      chunk3 = level.getChunk(x5/16, z5/16)
                      tiles2 = level.tileEntityAt(x5, y5, z5)

                      if tiles2 in chunk3.TileEntities and tiles2 != None:
                         chunk3.TileEntities.remove(tiles2)
                         chunk3.dirty = True
   else:
         chunk3 = level.getChunk(x1/16, z1/16)
         tiles2 = level.tileEntityAt(x1, y1, z1)

         if tiles2 in chunk3.TileEntities and tiles2 != None:
            chunk3.TileEntities.remove(tiles2)
            chunk3.dirty = True

**Comment by StealthyExpertX** [comment]
as for Entities I haven't tried really my self but one of these should work haven't
made any methods for entities yet, so this is all on the fly #Untested code.

#Delete Entities?
def getAndDeleteEnts(box):
    chunk = level.getChunk(box.minx/16, box.minz/16)

    for ent in chunk.Entities:
         level.removeEntitiesInBox(ent)

#Delete Entities In Box
def deleteEnts(box):

    for x5 in xrange(box.minx, box.maxx):

        for y5 in xrange(box.miny, box.maxy):

            for z5 in xrange(box.minz, box.maxz):

                chunk6 = level.getChunk(x5/16, z5/16)

                for ent3 in chunk6.Entities

                     chunk6.Entities.remove(ent3)

#Delete Entities On XYZ? Method
def deleteAllEnts(box, level, bool, x1, y1, z1):

    if bool == True:

        for x5 in xrange(box.minx, box.maxx):

            for y5 in xrange(box.miny, box.maxy):

                for z5 in xrange(box.minz, box.maxz):

                    chunk3 = level.getChunk(x5/16, z5/16)
                    ent = level.getEntitiesInBox(box)

                    if ent in chunk3.TileEntities and ent != None:
                       chunk3.Entities.remove(ent)
                       chunk3.dirty = True

else:
    chunk4 = level.getChunk(x1/16, z1/16)
    ent2 = level.getEntitiesInBox(box)

    if ent2 in chunk4.Entities and ent2 != None:
        chunk4.Entities.remove(ent2)
        chunk4.dirty = True

**Comment by StealthyExpertX** [comment]
As for Entities
I havent tried really my self
but this should work?

for ent in chunk.Entities:
    removeEntitiesInBox(end)
